export import Game = Phaser.Game;
export import Scene = Phaser.Scene;
export import Container = Phaser.GameObjects.Container;
export import GameObject = Phaser.GameObjects.GameObject;
export import Rectangle = Phaser.Geom.Rectangle;
export import Point = Phaser.Geom.Point;
export import Graphics = Phaser.GameObjects.Graphics;
export import Sprite = Phaser.GameObjects.Sprite;
export import Texture = Phaser.Textures.Texture;
export import EventEmitter = Phaser.Events.EventEmitter;
export import TileSprite = Phaser.GameObjects.TileSprite;
export import Size = Phaser.Structs.Size;
export import Scale = Phaser.Scale;
export import Pointer = Phaser.Input.Pointer;
export import EventData	= Phaser.Types.Input.EventData;
export import Vector2 = Phaser.Math.Vector2;
export import TransformMatrix = Phaser.GameObjects.Components.TransformMatrix;
export import BitmapMask = Phaser.Display.Masks.BitmapMask;
export import GeometryMask = Phaser.Display.Masks.GeometryMask;
export import Input = Phaser.Input;
export import Time = Phaser.Time;
export import PMath = Phaser.Math;

export import Easing = Phaser.Math.Easing;
export import Tweens = Phaser.Tweens;
export import Tween = Phaser.Tweens.Tween;
export import Timeline = Phaser.Tweens.Timeline;
export import Types = Phaser.Types;

export type MaskType = BitmapMask | GeometryMask;
export * from './plugins/StageScalePlugin';
require('./TweenPatch');