export * from "./Shape";
export * from "./SPoint";
export * from "./SLine";
export * from "./SRect";
export * from "./SCircle";
export * from "./SEllipse";
export * from "./SPolygon";
export * from "./SRegularPolygon";
export * from "./ShapeFactory";